/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica_medica.telas;

import br.edu.imepac.clinica_medica.administrativo.MainScreenAdmin;
import br.edu.imepac.clinica_medica.agendamento.MainScreenSchedule;
import br.edu.imepac.clinica_medica.atendimento.MainScreenTreatment;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ehf_v
 */
public class MainScreenAccess extends ScreenBase {
    private MainScreenAdmin mainScreenAdmin;
    private MainScreenSchedule mainScreenSchedule;
    private MainScreenTreatment mainScreenTreatment;

    /**
     * Creates new form MainScreenAccess
     */
    public MainScreenAccess() {
        initComponents();
        openAnotherWindows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        autorizationData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoApplication = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("CLINICA MÉDICA - INTEGRAÇÃO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 306, 29);

        autorizationData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        autorizationData.setText("01/01/2024 - 19:23:50");
        getContentPane().add(autorizationData);
        autorizationData.setBounds(150, 40, 170, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("EVERTON HIPÓLITO DE FREITA - \"ATENDENTE\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 60, 510, 20);

        logoApplication.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\logo-clinica.png")); // NOI18N
        logoApplication.setText("jLabel4");
        getContentPane().add(logoApplication);
        logoApplication.setBounds(690, 0, 370, 110);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Acesso autorizado....: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 130, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Acesso identificado..:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 60, 590, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        
        this.setBounds(315, 0 , screenSize.width - 315, 140) ; 
        logoApplication.setBounds(screenSize.width - 700, -5, 370, 110);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreenAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreenAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreenAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreenAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreenAccess().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorizationData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logoApplication;
    // End of variables declaration//GEN-END:variables

    private void openAnotherWindows() {
        mainScreenAdmin = new MainScreenAdmin();
        mainScreenAdmin.pack();
        mainScreenAdmin.setVisible(true);
        
        mainScreenSchedule = new MainScreenSchedule();
        mainScreenSchedule.pack();
        mainScreenSchedule.setVisible(true);
        
        mainScreenTreatment = new MainScreenTreatment();
        mainScreenTreatment.pack();
        mainScreenTreatment.setVisible(true);
    }
}
