/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica_medica.administrativo.especialidade;

import br.edu.imepac.clinica_medica.daos.EspecialidadeDAO;
import br.edu.imepac.clinica_medica.entidades.Especialidade;
import br.edu.imepac.clinica_medica.telas.ScreenBase;

import javax.swing.*;
import java.util.List;

/**
 * @author ehf_v
 */
public class EspecialidadeListagemScreen extends ScreenBase {

    /**
     * Creates new form FuncionarioCadastroScreen
     */
    public EspecialidadeListagemScreen() {
        initComponents();
        positionScreen(315, 140, 695, 900);

        especialidadeDAO = new EspecialidadeDAO();

        loadDataFieldsFromDB();
    }

    private void loadDataFieldsFromDB() {
        List<Especialidade> especialidades = especialidadeDAO.readAll();

        tableEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[especialidades.size()][3],
                        new String[]{"Id", "Nome", "Descricao"}
                )
        );

        for (int i = 0; i < especialidades.size(); i++) {
            tableEspecialidades.setValueAt(especialidades.get(i).getId(), i, 0);
            tableEspecialidades.setValueAt(especialidades.get(i).getNome(), i, 1);
            tableEspecialidades.setValueAt(especialidades.get(i).getDescricao(), i, 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cancelarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEspecialidades = new javax.swing.JTable();
        cancelarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Listagem de especialidades");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 18, 380, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(6, 76, 1283, 3);

        cancelarButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\excluir.png")); // NOI18N
        cancelarButton.setText("Excluir");
        cancelarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelarButton.setIconTextGap(20);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEspecialidade(evt);
            }
        });
        getContentPane().add(cancelarButton);
        cancelarButton.setBounds(950, 250, 250, 80);

        editarButton.setBackground(new java.awt.Color(153, 204, 255));
        editarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editarButton.setForeground(new java.awt.Color(51, 0, 102));
        editarButton.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\save.png")); // NOI18N
        editarButton.setText("Editar");
        editarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editarButton.setIconTextGap(20);
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton);
        editarButton.setBounds(950, 340, 250, 80);

        tableEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableEspecialidades);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 910, 402);

        cancelarButton1.setBackground(new java.awt.Color(255, 153, 102));
        cancelarButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarButton1.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton1.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\encerrar.png")); // NOI18N
        cancelarButton1.setText("Fechar");
        cancelarButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelarButton1.setIconTextGap(20);
        cancelarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton1);
        cancelarButton1.setBounds(950, 430, 250, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (tableEspecialidades.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma especialidade para editar.");
        } else {
            Long id = (Long) tableEspecialidades.getValueAt(tableEspecialidades.getSelectedRow(), 0);
            new EspecialidadeEditarScreen(id).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void cancelarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarButton1ActionPerformed

    private void deleteEspecialidade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFuncionario
        if (tableEspecialidades.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma especialidade para excluir.");
        } else {
            Long id = (Long) tableEspecialidades.getValueAt(tableEspecialidades.getSelectedRow(), 0);
            especialidadeDAO.delete(id);
            loadDataFieldsFromDB();
            JOptionPane.showMessageDialog(this, "Especialidade excluída com sucesso.");
        }
    }//GEN-LAST:event_deleteFuncionario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarButton1;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableEspecialidades;
    // End of variables declaration//GEN-END:variables


    private EspecialidadeDAO especialidadeDAO;
}
