/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica_medica.administrativo.especialidade;

import br.edu.imepac.clinica_medica.daos.EspecialidadeDAO;
import br.edu.imepac.clinica_medica.entidades.Especialidade;
import br.edu.imepac.clinica_medica.telas.ScreenBase;

import javax.swing.*;

/**
 * @author ehf_v
 */
public class EspecialidadeEditarScreen extends ScreenBase {

    /**
     * Creates new form FuncionarioCadastroScreen
     */
    public EspecialidadeEditarScreen(Long id) {
        initComponents();

        positionScreen(315, 140, 695, 900);

        especialidadeId = id;
        especialidadeDAO = new EspecialidadeDAO();

        setFieldsFromForm();
    }

    private void setFieldsFromForm() {
        Especialidade especialidade = especialidadeDAO.read(especialidadeId);
        nomeField.setText(especialidade.getNome());
        descricaoField.setText(especialidade.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nomeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        limparBotton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Atualizar especialidades");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 18, 288, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(6, 76, 1283, 3);

        nomeField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(nomeField);
        nomeField.setBounds(110, 90, 1010, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Descrição");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 160, 76, 25);

        cancelarButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\encerrar.png")); // NOI18N
        cancelarButton.setText("Cancelar e fechar");
        cancelarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelarButton.setIconTextGap(20);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton);
        cancelarButton.setBounds(950, 760, 250, 80);

        salvarButton.setBackground(new java.awt.Color(153, 204, 255));
        salvarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvarButton.setForeground(new java.awt.Color(51, 0, 102));
        salvarButton.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\save.png")); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salvarButton.setIconTextGap(20);
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salvarButton);
        salvarButton.setBounds(40, 760, 220, 80);

        limparBotton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        limparBotton.setIcon(new javax.swing.ImageIcon("D:\\Imepac\\BACK\\2024-02\\clinica-medica-poo\\src\\main\\resources\\images\\limpar.png")); // NOI18N
        limparBotton.setText("Limpar campos");
        limparBotton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        limparBotton.setIconTextGap(20);
        limparBotton.setMaximumSize(new java.awt.Dimension(161, 70));
        limparBotton.setMinimumSize(new java.awt.Dimension(161, 70));
        limparBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBottonActionPerformed(evt);
            }
        });
        getContentPane().add(limparBotton);
        limparBotton.setBounds(690, 760, 240, 80);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setText("Nome");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 100, 60, 25);

        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setText("Campos em vermelho são obrigatórios o preenchimento.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 50, 360, 16);

        descricaoField.setColumns(20);
        descricaoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricaoField.setRows(5);
        jScrollPane1.setViewportView(descricaoField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 1070, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void limparBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBottonActionPerformed
    }//GEN-LAST:event_limparBottonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        if (descricaoField.getText().isEmpty() || nomeField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            Especialidade especialidade = new Especialidade(especialidadeId, nomeField.getText(), descricaoField.getText());
            especialidadeDAO.update(especialidade);
            JOptionPane.showMessageDialog(null, "Especialidade atualizada com sucesso.");

            this.dispose();
        }
    }//GEN-LAST:event_salvarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextArea descricaoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limparBotton;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables

    private EspecialidadeDAO especialidadeDAO;
    private Long especialidadeId;
}
