/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica_medica.administrativo;

import br.edu.imepac.clinica_medica.administrativo.especialidade.EspecialidadeCadastroScreen;
import br.edu.imepac.clinica_medica.administrativo.especialidade.EspecialidadeListagemScreen;
import br.edu.imepac.clinica_medica.administrativo.funcionario.FuncionarioCadastroScreen;
import br.edu.imepac.clinica_medica.administrativo.funcionario.FuncionarioListagemScreen;
import br.edu.imepac.clinica_medica.telas.ScreenBase;

import java.awt.*;

/**
 * @author ehf_v
 */
public class MainScreenAdmin extends ScreenBase {

    /**
     * Creates new form MainScreenAccess
     */
    public MainScreenAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        listarConvenioButton = new javax.swing.JButton();
        cadastrarConvenioButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        listarEspecialidadeButton = new javax.swing.JButton();
        cadastrarEspecialidadeButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        listarPerfilButton = new javax.swing.JButton();
        perfilFuncionarioButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        listarFuncionarioButton = new javax.swing.JButton();
        cadastrarFuncionarioButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        listarPacienteButton = new javax.swing.JButton();
        cadastrarPacienteButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        exitApplication = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Listagem de convênios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Área administrativa");

        listarConvenioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarConvenioButton.setText("Listagem de convênios");
        listarConvenioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        cadastrarConvenioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarConvenioButton.setText("Cadastrar convênios");
        cadastrarConvenioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        listarEspecialidadeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarEspecialidadeButton.setText("Listagem de especialidades");
        listarEspecialidadeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listarEspecialidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEspecialidadeButtonActionPerformed(evt);
            }
        });

        cadastrarEspecialidadeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarEspecialidadeButton.setText("Cadastrar especialidades");
        cadastrarEspecialidadeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cadastrarEspecialidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadeButtonActionPerformed(evt);
            }
        });

        listarPerfilButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarPerfilButton.setText("Listagem de perfis");
        listarPerfilButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listarPerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPerfilButtonActionPerformed(evt);
            }
        });

        perfilFuncionarioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        perfilFuncionarioButton.setText("Cadastrar perfis");
        perfilFuncionarioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        listarFuncionarioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarFuncionarioButton.setText("Listagem de funcionários");
        listarFuncionarioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listarFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFuncionarioButtonActionPerformed(evt);
            }
        });

        cadastrarFuncionarioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarFuncionarioButton.setText("Cadastrar funcionários");
        cadastrarFuncionarioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cadastrarFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioButtonActionPerformed(evt);
            }
        });

        listarPacienteButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarPacienteButton.setText("Listagem de pacientes");
        listarPacienteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPacienteButtonActionPerformed(evt);
            }
        });

        cadastrarPacienteButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarPacienteButton.setText("Cadastrar pacientes");
        cadastrarPacienteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        exitApplication.setBackground(new java.awt.Color(204, 0, 0));
        exitApplication.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitApplication.setForeground(new java.awt.Color(255, 255, 255));
        exitApplication.setText("Finalizar aplicação");
        exitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarEspecialidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listarEspecialidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perfilFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listarPerfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadastrarFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listarFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadastrarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 10, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarConvenioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listarConvenioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarConvenioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarConvenioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarEspecialidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarEspecialidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarPerfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perfilFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarFuncionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        int largura = 315; // Largura personalizada
        int altura = screenSize.height; // Altura total da tela
        this.setSize(largura, altura);
        this.setLayout(null); // Define o layout como livre (null)

        exitApplication.setBounds(12, screenSize.height - 100, 272, 51);
    }//GEN-LAST:event_formWindowOpened

    private void listarPerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPerfilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarPerfilButtonActionPerformed

    private void listarFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionarioButtonActionPerformed
        FuncionarioListagemScreen funcionarioListagemScreen = new FuncionarioListagemScreen();
        funcionarioListagemScreen.setVisible(true);
    }//GEN-LAST:event_listarFuncionarioButtonActionPerformed

    private void listarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPacienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarPacienteButtonActionPerformed

    private void cadastrarFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioButtonActionPerformed
        FuncionarioCadastroScreen funcionarioCadastroScreen = new FuncionarioCadastroScreen();
        funcionarioCadastroScreen.setVisible(true);

    }//GEN-LAST:event_cadastrarFuncionarioButtonActionPerformed

    private void cadastrarEspecialidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadeButtonActionPerformed
        EspecialidadeCadastroScreen especialidadeCadastroScreen = new EspecialidadeCadastroScreen();
        especialidadeCadastroScreen.setVisible(true);
    }//GEN-LAST:event_cadastrarEspecialidadeButtonActionPerformed

    private void listarEspecialidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEspecialidadeButtonActionPerformed
        EspecialidadeListagemScreen especialidadeListagemScreen = new EspecialidadeListagemScreen();
        especialidadeListagemScreen.setVisible(true);
    }//GEN-LAST:event_listarEspecialidadeButtonActionPerformed

    private void exitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitApplicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarConvenioButton;
    private javax.swing.JButton cadastrarEspecialidadeButton;
    private javax.swing.JButton cadastrarFuncionarioButton;
    private javax.swing.JButton cadastrarPacienteButton;
    private javax.swing.JButton exitApplication;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton listarConvenioButton;
    private javax.swing.JButton listarEspecialidadeButton;
    private javax.swing.JButton listarFuncionarioButton;
    private javax.swing.JButton listarPacienteButton;
    private javax.swing.JButton listarPerfilButton;
    private javax.swing.JButton perfilFuncionarioButton;
    // End of variables declaration//GEN-END:variables
}
